name: Build MSI Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: nuget restore

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution (Release)
        run: msbuild /t:Rebuild /p:Configuration=Release

      - name: Build MSI (VS Installer Project)
        shell: pwsh
        run: |
          $vdproj = Get-ChildItem -Recurse -Filter *.vdproj | Select-Object -First 1
          if (-not $vdproj) { Write-Error "No .vdproj found"; exit 1 }
          msbuild $vdproj.FullName /p:Configuration=Release

      - name: Find MSI and version
        id: msifind
        shell: pwsh
        run: |
          $msi = Get-ChildItem -Recurse -Filter *.msi | Select-Object -First 1
          if (-not $msi) { Write-Error "No MSI file found"; exit 1 }
          $version = (Get-Item $msi.FullName).VersionInfo.ProductVersion
          if (-not $version) { $version = "unknown" }
          $newName = "asgard-pc-agent-$version.msi"
          Copy-Item $msi.FullName $newName
          echo "msi_path=$newName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: asgard-pc-agent-msi
          path: ${{ env.msi_path }}